#!/bin/bash
#SBATCH -J InjectionRayMaPlayers                # Job name
#SBATCH -n 1                                    # Number of cores required
#SBATCH -c 16                                   # Number of threads per task
#SBATCH --mem-per-cpu=1G                        # Memory per core
#SBATCH -t 12:30:00                             # Duration of the job (Ex: 15 mins)
#SBATCH -p coc-cpu                              # Queue name (where job is submitted)
#SBATCH -o Report-%j.out                        # Combined output and error messages file
#SBATCH --mail-type=BEGIN,END,FAIL              # Mail preferences
#SBATCH --mail-user=staubman3@gatech.edu        # E-mail address for notifications
cd $SLURM_SUBMIT_DIR                            # Change to working directory

module load anaconda3                           # Load module dependencies
conda activate soccertwos
srun python injected_ray_ma_sp.py